### ISSUE TITLE
Coursera's SaaS course uses Rails

### ISSUE THREAD

**Issue by 5long** [awagener/iwanttolearnruby#12]
https://www.coursera.org/course/saas might wanna add this to the list?

**Comment by awagener** [comment]
That's a good idea, thanks. If you could make a pull request, that'd be awesome, otherwise I'll add it myself in the next few days. :-)

**Comment by awagener** [comment]
Fixed by https://github.com/awagener/iwanttolearnruby/pull/14, thanks @craigjennings11.
