### ISSUE TITLE
bad image on link on homepage

### ISSUE THREAD

**Issue by thatrubylove** [awagener/iwanttolearnruby#35]
Did I do that in the pr? Please give it a fix :)

![screen shot 2015-05-06 at 12 12 37 pm](https://cloud.githubusercontent.com/assets/5987052/7498835/5317dbb4-f3e9-11e4-99ef-f0f6d79163f6.png)

**Comment by awagener** [comment]
Ah yes, it expects an image in https://github.com/awagener/iwanttolearnruby/tree/gh-pages/images rather than a URL.  Sorry I didn't pick that up.  I'll have a look at it tonight - either add an image to the directory, or change the code.

**Comment by thatrubylove** [comment]
appreciate it! I've sent in a PR so I can just upload over the s3 image and it will update without the need for a new PR!
